export const GET_BREEDS = 'GET_BREEDS';

export const GET_BREEDS_BY_ID = 'GET_BREEDS_BY_ID';

export const GET_BREEDS_BY_NAME = 'GET_BREEDS_BY_NAME';

export const GET_TEMPERAMENT = 'GET_TEMPERAMENT';